services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=dev
      - MONGO_URI=${MONGO_URI}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_COLLECTION=${MONGO_COLLECTION}
    develop:
      watch:
        - path: .
          action: rebuild

  mongo:
    ports:
      - "27017:27017"
    command: --quiet
