# Deployment for Coolify
services:
  app:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      ENVIRONMENT: prod
      SERVER_PORT: 80
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - "80:80"

  postgres:
    container_name: postgres-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
