services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - GO_ENV=dev

  mongo:
    ports:
      - "27017:27017"
    command: --quiet
