services:
  app:
    container_name: url-shortener
    build:
      context: .
      dockerfile: Dockerfile.local
    environment:
      DB_HOST: postgres-db  # Must match postgres:container_name
      DB_PORT: 5432         # Must match postgres:ports
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ENVIRONMENT: dev
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
