services:
  app:
    build: .
    container_name: limitlink
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:8.0
    container_name: limitlink-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/limitlink-mongo --quiet
      interval: 5s
      timeout: 10s

volumes:
  mongo_data:
