services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    read_only: true
    networks:
      - limitlink-app

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: ${MONGO_URI}
      MONGO_NAME: ${MONGO_NAME}
    read_only: true
    tmpfs:
      - /tmp
    networks:
      - limitlink-app
      - limitlink-data

  mongo:
    image: mongo:8.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - limitlink-data
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:

networks:
  limitlink-app:
  limitlink-data:
